---
title: "Sha's Website"
output:
  html_document
---

I've decided to summarize and update the codes I'm using daily here.

Here's a working sample Dashboard, [take a look](dashboard.html)!

Summary:

1. Bar Chart: Total Snowfall in Winter Each Year.\
From the plot, we can see that year 2010 has the highest amount of snowfall overall.\
January have relatively stable and large amount of snowfall, while November have the lowest amount of snowfall in winter. \
The other three months in winter have a wider range of snowfall.

2. Lineplot: Average Highest and Lowest Temperature Each Year.\
From the plot, we can see that the average highest temperature and lowest temperature each year have the same pattern across years.\
The peck of both happened in 1998, with average highest temperature at 15.38 celsius degree and minimum temperature at 4.61 celsius degree.\
Both highest and lowest temperature are relatively stable across years.

3. Boxplot: Total Precipitation Each Year.\
Year 2010 has the highest median precipitation around 30.21k mm, with a highest monthly precipitation (outlier) at 67.83k.\
The total precipitation was stable before 2007, and increased in 2008, 2009 and 2010.

