---
title: "R Markdown Brief Review"
output:
  html_document:
      toc: true
      toc_float: true
---

## Code chunks and snippets

The hotkeys for inserting code chunk are `Ctrl + Alt + I`, while the hotkeys for knitting are `Ctrl + Shift + K`.\
Always give the chunk a name `{r chunk_name}`, so when we have bugs, we can look back and find that chunk immediately.

Beyond the name, we can customize the behavior of your code chunk via options defined in the chunk header. Some common options are: 

* eval = FALSE: code will be displayed but not executed; results are not included.
* echo = FALSE: code will be executed but not displayed; results are included.
* include = FALSE: code will be executed but not displayed; results are not included. (This is common for load the libraries)
* message = FALSE and warning = FALSE: prevents messages and warnings from being displayed. (This is common for the steps that produces unimportatnt messages and warnings)
* results = hide and fig.show = hide: prevents results and figures from being shown, respectively. (There are few more commands for the figures)
* collapse = TRUE: output will be collapsed into a single block at shown at the end of the chunk.
* error: errors in code will stop rendering when FALSE; errors in code will be printed in the doc when TRUE. The default is FALSE and you should almost never change it.

Inserting brief code snippets inline is often helpful; we can use them for a brief summary of the sample size or statistics in text by inserting code inline using `r `, often in conjunction with the `format()` function to clean up the output.

## Problems
#### Line break
To force a line break, there are several easy ways. We can simply place two empty spaces at the end of a line, however, it's hard to tell when we edit the file. The way I use is to place a backslash `\` at the end of the line.
In addition, if we want an empty line, we can add a `<br>` in that empty line.

#### Bulletpoints
Sometimes when we use * for the bulletpoints it won't work. It is because that it needs a blank line before the list in R Markdown if it is not directly after a header or by itself.

## Resources
* [R Markdown Cheatsheet](https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)
* [R Markdown Basics](https://markdown-guide.readthedocs.io/en/latest/basics.html#blockquotes)